name: build Docker image, optionally publish it

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: test
    uses: './.github/workflows/test.yml'

  build-publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: log into the Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        tags: |
          entur/lamassu:latest
        platforms: linux/amd64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max
